In [67]:
#!pip install emoji

In [1]:
import emoji

In [2]:
#print(emoji.emojize('Python is :thumbs_up:'))

In [3]:
#print(emoji.emojize('Python is :thumbsup:', use_aliases=True))

In [2]:
print(emoji.UNICODE_EMOJI)

{u'\u2604': u':comet:', u'\U0001f38d': u':pine_decoration:', u'\U0001f68f': u':bus_stop:', u'\U0001f50e': u':magnifying_glass_tilted_right:', u'\U0001f991': u':squid:', u'\U0001f933\U0001f3fb': u':selfie_light_skin_tone:', u'\U0001f4a3': u':bomb:', u'\U0001f468\u200d\U0001f373': u':man_cook:', u'\U0001f933\U0001f3ff': u':selfie_dark_skin_tone:', u'\U0001f933\U0001f3fe': u':selfie_medium-dark_skin_tone:', u'\U0001f933\U0001f3fd': u':selfie_medium_skin_tone:', u'\U0001f926': u':person_facepalming:', u'\U0001f926\U0001f3fd\u200d\u2642\ufe0f': u':man_facepalming_medium_skin_tone:', u'\U0001f438': u':frog_face:', u'\U0001f93e\u200d\u2642\ufe0f': u':man_playing_handball:', u'\U0001f4b4': u':yen_banknote:', u'\U0001f468\u200d\u2764\ufe0f\u200d\U0001f468': u':couple_with_heart_man_man:', u'\U0001f3cd': u':motorcycle:', u'\U0001f575\U0001f3fc\u200d\u2640\ufe0f': u':woman_detective_medium-light_skin_tone:', u'\U0001f54e': u':menorah:', u'\U0001f9d1': u':adult:', u'\U0001f9d8\U0001f3fd\u200d\u264

In [3]:
print(emoji.emojize(':bus_stop:'))

🚏


In [4]:
import numpy as np
import pandas as pd
import emoji

from keras.models import Sequential
from keras.layers import Dense, Input, Dropout, SimpleRNN,LSTM, Activation
from keras.utils import np_utils

import matplotlib.pyplot as plt

Using TensorFlow backend.


In [5]:
train = pd.read_csv('train_emoji.csv',header=None)
test = pd.read_csv('test_emoji.csv',header=None)

In [6]:
train.head()

0  1   2     3
0           never talk to me again  3 NaN   NaN
1  I am proud of your achievements  2 NaN   NaN
2   It is the worst day in my life  3 NaN   NaN
3                 Miss you so much  0 NaN   [0]
4                     food is life  4 NaN   NaN

In [7]:
test.head()

0  1
0             I want to eat\t  4
1         he did not answer\t  3
2            he got a raise\t  2
3      she got me a present\t  0
4  ha ha ha it was so funny\t  2

In [8]:
emoji_dict = { 0 : ":beating_heart:", 1 : ":baseball:", 2 : ":smile:", 3 : ":disappointed:", 4 : ":fork_and_knife:"}

In [9]:
for ix in emoji_dict.keys():#by default emojize iterates over keys
    print(ix)
    print(emoji.emojize(emoji_dict[ix], use_aliases=True))
    

0
💓
1
⚾
2
😄
3
😞
4
🍴


In [10]:
X_train=train[0]
Y_train=train[1]
X_test = test[0]
Y_test = test[1]

In [11]:
X_train.shape,Y_train.shape

((132,), (132,))

In [12]:
X_test.shape,Y_test.shape

((56,), (56,))

In [13]:
X_train[0]

'never talk to me again'

In [14]:
print(emoji.emojize(emoji_dict[3], use_aliases=True))

😞


In [15]:
for ix in range(X_train.shape[0]):
    X_train[ix] = X_train[ix].lower().split()#convert the sentence into list of words
    
for ix in range(X_test.shape[0]):
    X_test[ix] = X_test[ix].split()
    
    

/home/loveleen/.local/lib/python2.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
/home/loveleen/.local/lib/python2.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """


In [16]:
X_train[0]

['never', 'talk', 'to', 'me', 'again']

In [17]:
def read_glove_vecs(glove_file):
    with open(glove_file, 'r') as f:
        words = set()#stores unique words
        word_to_vec_map = {}
        for line in f:
            #print(line)
            line = line.strip().split()#strip removes whitespaces and split changes it to list
            #print(line)
            curr_word = line[0]
            words.add(curr_word)
            word_to_vec_map[curr_word] = np.array(line[1:], dtype=np.float64)
            #print(word_to_vec_map)
        
        i = 1
        words_to_index = {}
        index_to_words = {}
        for w in sorted(words):
            words_to_index[w] = i
            index_to_words[i] = w
            i = i + 1
        #print(words_to_index)
        #print(index_to_words)
    return words_to_index, index_to_words, word_to_vec_map

In [18]:
words_to_index, index_to_words, word_to_vec_map=read_glove_vecs("glove.6B.50d.txt")

In [19]:
word_to_vec_map["happy"]

array([ 0.092086,  0.2571  , -0.58693 , -0.37029 ,  1.0828  , -0.55466 ,
       -0.78142 ,  0.58696 , -0.58714 ,  0.46318 , -0.11267 ,  0.2606  ,
       -0.26928 , -0.072466,  1.247   ,  0.30571 ,  0.56731 ,  0.30509 ,
       -0.050312, -0.64443 , -0.54513 ,  0.86429 ,  0.20914 ,  0.56334 ,
        1.1228  , -1.0516  , -0.78105 ,  0.29656 ,  0.7261  , -0.61392 ,
        2.4225  ,  1.0142  , -0.17753 ,  0.4147  , -0.12966 , -0.47064 ,
        0.3807  ,  0.16309 , -0.323   , -0.77899 , -0.42473 , -0.30826 ,
       -0.42242 ,  0.055069,  0.38267 ,  0.037415, -0.4302  , -0.39442 ,
        0.10511 ,  0.87286 ])

In [20]:
def avg_vector(words):
    
    ans = word_to_vec_map[words[0]]
   # print(ans)
    for i in range(1,len(words)):
        ans = np.add(ans,word_to_vec_map[words[i]])
    ans = ans/float(len(words))
    return ans    
    

In [21]:
ans=avg_vector(X_train[0])

In [22]:
print(ans)

[ 9.718460e-02  1.743740e-02  5.284300e-02 -4.368060e-01  2.756132e-01
 -1.426688e-01 -6.120520e-01  4.716140e-01 -6.059740e-01  1.566594e-01
 -8.662400e-02  4.906620e-01 -6.480320e-01 -1.612960e-01  8.897200e-01
  4.867520e-01  4.601260e-02 -8.363342e-02 -2.288840e-01 -4.151500e-01
 -1.140000e-02  6.407600e-01  5.954280e-01  1.780868e-01  7.128668e-01
 -2.072760e+00 -3.161338e-01  1.869920e-01  6.583040e-01 -6.969300e-01
  3.172380e+00  5.411100e-01 -5.941440e-01 -3.028740e-01 -2.285386e-01
 -2.899120e-01  2.006040e-01  1.053064e-01 -3.933000e-02 -4.483020e-01
 -1.353596e-01 -2.031200e-03 -2.454976e-01  1.305460e-01 -1.976000e-02
  2.025340e-02 -1.199070e-01 -2.522034e-01 -2.197784e-01  3.076060e-01]


In [23]:
X_numbers=np.zeros((132,50))

In [24]:
for i in range(X_train.shape[0]):
    X_numbers[i]=avg_vector(X_train[i])

In [25]:
print(X_numbers.shape)

(132, 50)


In [26]:
embedding_matrix_train = np.zeros((X_train.shape[0], 10, 50))
embedding_matrix_test = np.zeros((X_test.shape[0], 10, 50))
i=0
for ix in range(X_train.shape[0]):
    for ij in range(len(X_train[ix])):
        embedding_matrix_train[ix][ij] = word_to_vec_map[X_train[ix][ij].lower()]
        
for ix in range(X_test.shape[0]):
    for ij in range(len(X_test[ix])):
        embedding_matrix_test[ix][ij] = word_to_vec_map[X_test[ix][ij].lower()]      

In [27]:
embedding_matrix_train

array([[[ 9.5387e-02, -1.6865e-01, -1.1514e-01, ..., -4.2103e-01,
         -5.3817e-01,  1.3738e-01],
        [-3.4604e-02,  4.1087e-01, -9.7368e-02, ...,  5.6204e-01,
         -5.9770e-01,  9.5068e-01],
        [ 6.8047e-01, -3.9263e-02,  3.0186e-01, ..., -7.3297e-02,
         -6.4699e-02, -2.6044e-01],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]],

       [[ 1.1891e-01,  1.5255e-01, -8.2073e-02, ..., -5.7512e-01,
         -2.6671e-01,  9.2121e-01],
        [ 3.4664e-01,  3.9805e-01,  4.8970e-01, ...,  8.6576e-02,
          3.4037e-01,  1.3588e+00],
        [-5.9180e-01,  2.7671e-01, -4.6971e-01, ..., -2.0055e-01,
         -2.6487e-01,  5.7981e-01],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  

In [28]:
model = Sequential()
model.add(SimpleRNN(64, input_shape=(10,50), return_sequences=True))
model.add(Dropout(0.5))
model.add(SimpleRNN(64, return_sequences=False))
model.add(Dropout(0.5))
model.add(Dense(5))
model.add(Activation('softmax'))


In [29]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [30]:
Y_train.shape

(132,)

In [31]:
Y_onehot=np_utils.to_categorical(Y_train)

In [32]:
print(Y_onehot)

[[0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1.

In [33]:
model.fit(embedding_matrix_train,Y_onehot,epochs=100)

Epoch 1/100
132/132 [==============================] - 2s 12ms/step - loss: 2.0206 - acc: 0.1970
Epoch 2/100
132/132 [==============================] - 0s 362us/step - loss: 1.7541 - acc: 0.2955
Epoch 3/100
132/132 [==============================] - 0s 311us/step - loss: 1.7454 - acc: 0.2576
Epoch 4/100
132/132 [==============================] - 0s 353us/step - loss: 1.6589 - acc: 0.3485
Epoch 5/100
132/132 [==============================] - 0s 425us/step - loss: 1.5508 - acc: 0.3333
Epoch 6/100
132/132 [==============================] - 0s 350us/step - loss: 1.4228 - acc: 0.4394
Epoch 7/100
132/132 [==============================] - 0s 365us/step - loss: 1.3850 - acc: 0.3939
Epoch 8/100
132/132 [==============================] - 0s 374us/step - loss: 1.3307 - acc: 0.4545
Epoch 9/100
132/132 [==============================] - 0s 384us/step - loss: 1.4013 - acc: 0.4318
Epoch 10/100
132/132 [==============================] - 0s 336us/step - loss: 1.2370 - acc: 0.4773
Epoch 11/100
132/132

132/132 [==============================] - 0s 284us/step - loss: 0.0415 - acc: 0.9924
Epoch 84/100
132/132 [==============================] - 0s 308us/step - loss: 0.0402 - acc: 1.0000
Epoch 85/100
132/132 [==============================] - 0s 289us/step - loss: 0.0271 - acc: 1.0000
Epoch 86/100
132/132 [==============================] - 0s 398us/step - loss: 0.0472 - acc: 0.9848
Epoch 87/100
132/132 [==============================] - 0s 387us/step - loss: 0.0331 - acc: 0.9924
Epoch 88/100
132/132 [==============================] - 0s 264us/step - loss: 0.0460 - acc: 0.9924
Epoch 89/100
132/132 [==============================] - 0s 296us/step - loss: 0.0483 - acc: 0.9924
Epoch 90/100
132/132 [==============================] - 0s 318us/step - loss: 0.0328 - acc: 1.0000
Epoch 91/100
132/132 [==============================] - 0s 301us/step - loss: 0.0333 - acc: 1.0000
Epoch 92/100
132/132 [==============================] - 0s 264us/step - loss: 0.0255 - acc: 0.9924
Epoch 93/100
132/132 [=

In [34]:
i=7
print(train[0][i])

['congratulations', 'on', 'your', 'acceptance']


In [35]:
output=np.argmax(model.predict(embedding_matrix_train),axis=1)

In [36]:
Y_train[:10]

0    3
1    2
2    3
3    0
4    4
5    0
6    3
7    2
8    3
9    1
Name: 1, dtype: int64

In [37]:
np.sum(output==Y_train)

132

In [38]:
text="I love ice cream"
text=text.split()
x_ = np.zeros((1,10,50))
for ix in range(len(text)):
    x_[0][ix]=word_to_vec_map[text[ix].lower()]

In [39]:
emojji_label_predict=np.argmax(model.predict(x_))

In [40]:
print(emojji_label_predict)

4


In [41]:
print(emoji.emojize(emoji_dict[emojji_label_predict],use_aliases=True))

🍴


In [42]:
model = Sequential()
model.add(LSTM(128, input_shape=(10,50), return_sequences=True))
model.add(Dropout(0.5))
model.add(LSTM(128, return_sequences=False))
model.add(Dropout(0.5))
model.add(Dense(5))
model.add(Activation('softmax'))

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 10, 128)           91648     
_________________________________________________________________
dropout_3 (Dropout)          (None, 10, 128)           0         
_________________________________________________________________
lstm_2 (LSTM)                (None, 128)               131584    
_________________________________________________________________
dropout_4 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 5)                 645       
_________________________________________________________________
activation_2 (Activation)    (None, 5)                 0         
Total params: 223,877
Trainable params: 223,877
Non-trainable params: 0
_________________________________________________________________


In [43]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [44]:
model.fit(embedding_matrix_train,Y_onehot,epochs=100)

Epoch 1/100
132/132 [==============================] - 1s 10ms/step - loss: 1.5904 - acc: 0.2500
Epoch 2/100
132/132 [==============================] - 0s 1ms/step - loss: 1.5156 - acc: 0.3561
Epoch 3/100
132/132 [==============================] - 0s 1ms/step - loss: 1.4509 - acc: 0.3712
Epoch 4/100
132/132 [==============================] - 0s 1ms/step - loss: 1.3993 - acc: 0.4091
Epoch 5/100
132/132 [==============================] - 0s 1ms/step - loss: 1.2789 - acc: 0.4924
Epoch 6/100
132/132 [==============================] - 0s 1ms/step - loss: 1.1678 - acc: 0.5227
Epoch 7/100
132/132 [==============================] - 0s 1ms/step - loss: 1.0314 - acc: 0.5909
Epoch 8/100
132/132 [==============================] - 0s 1ms/step - loss: 0.9204 - acc: 0.6667
Epoch 9/100
132/132 [==============================] - 0s 1ms/step - loss: 0.8548 - acc: 0.7045
Epoch 10/100
132/132 [==============================] - 0s 1ms/step - loss: 0.6694 - acc: 0.7652
Epoch 11/100
132/132 [================

132/132 [==============================] - 0s 1ms/step - loss: 0.0775 - acc: 0.9848
Epoch 86/100
132/132 [==============================] - 0s 1ms/step - loss: 0.0724 - acc: 0.9924
Epoch 87/100
132/132 [==============================] - 0s 1ms/step - loss: 0.0481 - acc: 0.9848
Epoch 88/100
132/132 [==============================] - 0s 1ms/step - loss: 0.0425 - acc: 0.9924
Epoch 89/100
132/132 [==============================] - 0s 1ms/step - loss: 0.1458 - acc: 0.9470
Epoch 90/100
132/132 [==============================] - 0s 1ms/step - loss: 0.0291 - acc: 1.0000
Epoch 91/100
132/132 [==============================] - 0s 1ms/step - loss: 0.0714 - acc: 0.9848
Epoch 92/100
132/132 [==============================] - 0s 1ms/step - loss: 0.0165 - acc: 1.0000
Epoch 93/100
132/132 [==============================] - 0s 1ms/step - loss: 0.0300 - acc: 0.9924
Epoch 94/100
132/132 [==============================] - 0s 1ms/step - loss: 0.0187 - acc: 1.0000
Epoch 95/100
132/132 [=====================

In [45]:
output=np.argmax(model.predict(embedding_matrix_train),axis=1)

In [46]:
np.sum(output==Y_train)

132

In [48]:
text="aashish is my best friend"
text=text.split()
x_ = np.zeros((1,10,50))
for ix in range(len(text)):
    x_[0][ix]=word_to_vec_map[text[ix].lower()]

In [49]:
emojji_label_predict=np.argmax(model.predict(x_))

In [50]:
print(emojji_label_predict)

0


In [51]:
print(emoji.emojize(emoji_dict[emojji_label_predict],use_aliases=True))

💓
